### ISSUE TITLE
Extend config to support sorting parameter

### ISSUE THREAD

**Issue by khayyamsaleem** [marekm4/color-extractor#3]
There's an interest from [a consumer of this project](https://github.com/gohugoio/hugo/issues/10450) ([hugo](github.com/gohugoio/hugo)) to be able to support different ways of sorting the output from the color extractor.

Do you think this capability belongs in `color_extractor.ExtractColorsWithConfig`?

Could the config be extended to support keys like `dominance` (default), `luminance`, and order-directions like `asc` and `desc`?

Happy to help with the implementation, just wanted to open up the discussion if you're willing to maintain this project.

**Comment by marekm4** [comment]
Hi @khayyamsaleem 

Whole purpose of this library is to find dominant color(s). That's why this is only way, you can easily reverse order or add different sorting option in client code.

If [hugo](https://github.com/gohugoio/hugo) would like to add sorting they can easily do it.
